Forzando error en la practica

diff --git a/.github/workflows/basic-workflow.yaml b/.github/workflows/basic-workflow.yaml
--- a/.github/workflows/basic-workflow.yaml
+++ b/.github/workflows/basic-workflow.yaml
@@ -1,5 +1,4 @@
 name: Basic Workflow
-
 on:
   push:
     branches:
@@ -9,7 +8,10 @@ jobs:
   do-things:
     name: Do Things
     runs-on: ubuntu-latest
-
     steps:
       - name: Logrado
-        run: echo "Logrado!"
+        run: echo "Lo he logrado!"
+      - name: Provocando un error
+        run: |
+          echo "Cometí un error!"
+          exit 1
